[package]
name = "wasm-pkg-common"
description = "Wasm Package common types and configuration"
repository = "https://github.com/bytecodealliance/wasm-pkg-tools/tree/main/crates/wasm-pkg-common"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[features]
metadata-client = ["dep:reqwest"]
tokio = ["dep:tokio"]

[dependencies]
anyhow = { workspace = true }
bytes = "1.6.0"
dirs = "5.0.1"
futures-util = "0.3.30"
http = "1.1.0"
reqwest = { version = "0.12.0", features = ["json"], optional = true }
semver = "1.0.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.8"
tokio = { workspace = true, features = ["io-util", "fs"], optional = true }
toml = "0.8.13"
thiserror = "1.0"
tracing = "0.1"
wit-parser = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
