on: [push, pull_request]

name: CI

jobs:
  run-ci:
    name: Run CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            additional_test_flags: ""
          - os: windows-latest
            additional_test_flags: "--no-default-features"
          - os: macos-latest
            additional_test_flags: "--no-default-features"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "wasm32-wasi"
      # We have to run these separately so we can deactivate a feature for one of the tests
      - name: Run client tests
        working-directory: ./crates/wasm-pkg-client
        run: cargo test ${{ matrix.additional_test_flags }}
      - name: Run other tests
        run: cargo test --workspace --exclude wasm-pkg-client
      - name: Run cargo clippy
        run: cargo clippy --all --workspace 