on: [push, pull_request]

name: CI

jobs:
  run-ci:
    name: Run CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            run_lints: true
            test_wasm_build: true
          - os: windows-latest
            docker_tests_flags: "--no-default-features"
          - os: macos-latest
            docker_tests_flags: "--no-default-features"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "wasm32-wasip1"

      - name: Run lints
        if: matrix.run_lints
        run: |
          cargo clippy --workspace --no-default-features
          cargo clippy --workspace --all-features

      - name: Run tests
        run: cargo test --workspace --exclude wasm-pkg-client --exclude wkg

      # NOTE: Docker tests are only run on linux because other platforms haven't
      # always worked consistently.
      - name: Run wasm-pkg-client tests
        run: cargo test -p wasm-pkg-client ${{ matrix.docker_tests_flags }}
      - name: Run wkg tests
        run: cargo test -p wkg ${{ matrix.docker_tests_flags }}

      - name: Test wasm32-wasip1 build for wasm-pkg-common
        if: matrix.test_wasm_build
        run: cargo build -p wasm-pkg-common --target wasm32-wasip1