on: [push, pull_request]

name: CI

jobs:
  run-ci:
    name: Run CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run cargo test
        run: cargo test --all --workspace
      - name: Run cargo clippy
        run: cargo clippy --all --workspace 