on: [push, pull_request]

name: CI

jobs:
  run-ci:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: |
          ci/get-oras.sh
          echo "/tmp/ci-bin" >> $GITHUB_PATH
      - name: Run cargo test
        run: cargo test --all --workspace
      - name: Run cargo clippy
        run: cargo clippy --all --workspace 